### ISSUE TITLE
Details component should be responsive

### ISSUE THREAD

**Issue by andbudha** [andbudha/zodiac#3]
1. If you make the screen smaller you will see that the displayed data in the Details component gets squeezed. Fix that, please.
2.  Please, set the font color as agreed: #161D6F and #fff where the background is blue
![details](https://github.com/user-attachments/assets/4d90bb18-3018-4c78-ace2-153706949a2f)

**Comment by MohammadBaseer** [comment]
Details component Modified

**Comment by MohammadBaseer** [comment]
Details component Modified
